### ISSUE TITLE
Wrong formatting with outer single quotes and inner double quotes

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/zpretty#109]
In `plone.app.caching` the `controlpanel.pt` has this:

```
data-pat-plone-modal='{"actionOptions": {"disableAjaxFormSubmit":true}}'
```

`zpretty` turns this into all double quotes:

```
data-pat-plone-modal="{"actionOptions": {"disableAjaxFormSubmit":true}}"
```

Then run `zpretty` on it a second time, and it becomes:

```
actionoptions":=""
{"disableajaxformsubmit":true}}"=""
data-pat-plone-modal="{"
```

I hope `zpretty` can be convinced to not do this. :-)

Workaround/solution: fix the template manually (I am doing that in a `plone.app.caching` PR) to use outer double quotes and inner single quotes:

```
data-pat-plone-modal="{'actionOptions': {'disableAjaxFormSubmit':true}}"
```

`zpretty` does not change this anymore, and the modal works when I try it.

**Comment by ale-rt** [comment]
I released zpretty 3.0.2 which should fix this issue
