### ISSUE TITLE
"attribute sorting is first semantic and then alphabetic" - more information about semantic in zcml files?

### ISSUE THREAD

**Issue by idgserpro** [collective/zpretty#11]
An example of running `zpretty --zcml` (on the left is the original, on the right after running `zpretty --zcml`):

![Seleção_182](https://user-images.githubusercontent.com/8203476/62377344-f376c300-b518-11e9-9616-d36ed4abb7b4.png)

**Comment by ale-rt** [comment]
Thanks for the interest :)
zcml attribute sorting is unfinished stuff.

The planned goal is to have for each element a sorting order that matches exactly the arguments of the corresponding zcml function.
I.e. for registerProfile:
https://github.com/zopefoundation/Products.GenericSetup/blob/master/Products/GenericSetup/zcml.py#L89-L92
But unluckily I still have to implement this feature.

**Comment by ale-rt** [comment]
I would say that with #32 this can be considered closed.
In case you do not agree with the proposed sorting criteria, please open another issue :)
