### ISSUE TITLE
Doubling xml version line

### ISSUE THREAD

**Issue by gforcada** [collective/zpretty#118]
While preparing a `plone/meta` formatting of `Products.PortalTransforms` I noticed that running `zpretty` on it, it does something a bit weird:

```html
<?xml version="1.0" encoding="utf-8"?>
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      lang="en"
      xml:lang="en"
>
```

Notice the first two lines, removing one of them and re-running `zpretty` adds back the removed line 🤔 not sure what's going on there 🤷🏾 

One of the few files that this happens:

- `Products/PortalTransforms/tests/input/test_lynx.html`
- `Products/PortalTransforms/tests/input/test_safehtml.html`
- `Products/PortalTransforms/tests/output/org-news.html`

Actually, I noticed, that at any new run of `zpretty` it adds a new `<?xml version="1.0" encoding="utf-8"?>` 🤔

**Comment by ale-rt** [comment]
This was fixed by #120
