### ISSUE TITLE
Some empty attributes are done wrong

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/zpretty#119]
See https://github.com/plone/plone.app.z3cform/pull/162#issuecomment-1478750427

**Comment by ale-rt** [comment]
Uhm, `zpretty` has a list of boolean attributes:
https://github.com/collective/zpretty/blob/293d19cf6837d744211d551e93bae81baa2ef317/zpretty/attributes.py#L25-L51

I think that the expected behavior is to remove the boolean attribute if the value is empty.

**Comment by thet** [comment]
Boolean attributes are true when they are present, regardless of their value. But it should be ok to remove the asignment part, like in maurits example.
Also see: https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML

**Comment by ale-rt** [comment]
Yeah, I have been thinking as well about this.
I am kind of prone to close this as won't fix.
I still have no clear idea on what caused the test failure in https://github.com/plone/plone.app.z3cform/pull/162.
I kind of like to have boolean attributes to be rendered valueless.

**Comment by mauritsvanrees** [comment]
So I guess if you have this in your template, the template works fine:

```
disabled=""
tal:attributes="disabled python:True"
```

But then `zpretty` changes it to this:

```
disabled
tal:attributes="disabled python:True"
```

And then zope.pagetemplate or Chameleon or whatever somehow does not know how to apply the `tal:attributes` anymore.  Can that be it?  That is my working theory now.


That is not nice, but not really sure where to fix this in code.  And it can easily be fixed in the template itself: there is no need to have either `disabled` or `disable=""` or `disabled="disabled"` in there if you are going to replace it with `tal:attributes` anyway.

I guess it is fine to close this issue.

**Comment by ale-rt** [comment]
It seems to me that chameleon does not behave properly with boolean attributes:
```
[ale@flo chameleon]$ cat test.pt
<input required="" tal:attributes="required string:required">
<input required tal:attributes="required string:required">
<input required foo="bar" tal:attributes="required string:required">

[ale@flo chameleon]$ cat test.py
from chameleon import PageTemplate

with open("test.pt") as f:
    print(PageTemplate(f.read())())

[ale@flo chameleon]$ python test.py 
<input required="required">
<input requiredrequired>
<input requiredrequired foo="bar">
```
