### ISSUE TITLE
Do not turn angle brackets to html entities

### ISSUE THREAD

**Issue by gforcada** [collective/zpretty#124]
In [plone.app.content](https://github.com/plone/plone.app.content) in file [browser/contents/templates/properties.pt](https://github.com/plone/plone.app.content/blob/3ab4efd71bfe09348ed837e14322eef24832e36b/plone/app/content/browser/contents/templates/properties.pt#L46-L55) there is this snippet:

```html
  <% if (data.languages) { %>
  <div class="mb-2">
    <label class="form-label" i18n:translate="label_language">Language</label>
    <select class="form-select" name="language">
      <% _.each(data.languages, function (lang) { %>
        <option value="<%= lang.value %>"><%= lang.title %></option>
      <% }); %>
    </select>
  </div>
  <% } %>
```

Running `zpretty` on it turns this snippet into

```html
  &lt;% if (data.languages) { %&gt;
  <div class="mb-2">
    <label class="form-label"
           i18n:translate="label_language"
    >Language</label>
    <select class="form-select"
            name="language"
    >
      &lt;% _.each(data.languages, function (lang) { %&gt;
      <option value="&lt;%= lang.value %&gt;">&lt;%= lang.title %&gt;</option>
      &lt;% }); %&gt;
    </select>
  </div>
  &lt;% } %&gt;
```

See the related PR that tried to add `plone/meta` on that repository for a few more inputs: https://github.com/plone/plone.app.content/pull/262

I thought this was reported already, but I do fail to see the issue/PR about it, so in case of doubt, I'm reporting it (again?) 😄 

Any idea how to fix this? 🤔

**Comment by ale-rt** [comment]
`<>` are not valid characters. IMO zpretty does the right thing.
If that is not an xml file rename I would suggest to rename it, e.g. to `jsx`.
