### ISSUE TITLE
zpretty pre-commit hook with exclude don't work

### ISSUE THREAD

**Issue by 1letter** [collective/zpretty#142]
@ale-rt 

i call zpretty via commandline directly, it works, fine!

```
zpretty --include=".*.(zcml|xml)$" --extend-exclude="/(sample)/" src
```

but in the .pre-commit-config.yaml i use this snippet and this won't work:
```
-   repo: https://github.com/collective/zpretty
    rev: 3.1.0
    hooks:
    -   id: zpretty
        files: ".*.(zcml|xml)$"
        args: ["--extend-exclude='/(sample)/'"]
```

Background: in the 'sample' directory are XML files in ISO 8859-1 format, and the pre-commit fails with:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 394: invalid start byte
```
Any Ideas for a workaround or the correct config of the pre-commit?

**Comment by ale-rt** [comment]
Try with something like this:
```
[ale@flo dfsajhfdjkls]$ cat .pre-commit-config.yaml 
repos:
  - repo: https://github.com/collective/zpretty
    rev: 3.1.0
    hooks:
    -   id: zpretty
        name: zpretty with excludes
        files: ".*.(zcml|xml)$"
        args:
          - --extend-exclude='/(sample)/'
  - repo: https://github.com/collective/zpretty
    rev: 3.1.0
    hooks:
    -   id: zpretty
        name: zpretty with checks
        files: ".*.(zcml|xml)$"
        args:
          - --check

[ale@flo dfsajhfdjkls]$ pre-commit run --all
zpretty with excludes....................................................Passed
zpretty with checks......................................................Failed
- hook id: zpretty
- exit code: 1

This file would be rewritten: sample/a.zcml
```

Theoretically, you should also be able to pass the encoding with `--encoding` if you want.

**Comment by 1letter** [comment]
@ale-rt 

The rewrite to 
```
args:
   - --extend-exclude="/(sample)/"
 ```
doesn't help. I get the same encoding error like before. The switch to another encoding is not an option, because in the repro lives zcml files with utf-8 enocding. But thanks for your hint.

**Comment by ale-rt** [comment]
That's really strange... if you see my example the two checks show different results suggesting that the parameters are properly applied :/.

This is the directory structure I used for testing:
```
[ale@flo tmp]$ find /home/ale/tmp/dfsajhfdjkls|grep -v git
/home/ale/tmp/dfsajhfdjkls
/home/ale/tmp/dfsajhfdjkls/.pre-commit-config.yaml
/home/ale/tmp/dfsajhfdjkls/sample
/home/ale/tmp/dfsajhfdjkls/sample/a.zcml
```

**Comment by 1letter** [comment]
@ale-rt 
i added a pdb to the ```good_paths``` property. but if i run the `pre-commit run --all` it don't stop @the breakpoint. is this the normal behavior? if i run `zpretty` via console the execution stops at the pdb breakpoint.

**Comment by ale-rt** [comment]
pre-commit install the hook here:
```
~/.cache/pre-commit/
```
Maybe you put the pdb in the wrong zpretty?

**Comment by 1letter** [comment]
@ale-rt yes, that was the error. i will debug my problem in `~/.cache/pre-commit/`

**Comment by 1letter** [comment]
@ale-rt  my Workaround: 

```
-   repo: https://github.com/collective/zpretty
    rev: 3.1.0
    hooks:
    -   id: zpretty
        name: zpretty xml with excludes
        files: "^((?!sample).)*.xml$"
```

**Comment by ale-rt** [comment]
I am glad you found a way :)

If you are interested, there is also the exclude parameter in pre-commit:

- https://pre-commit.com/#top_level-exclude
