### ISSUE TITLE
Support ZCML styleguide

### ISSUE THREAD

**Issue by ale-rt** [collective/zpretty#3]
See:

- https://zopetoolkit.readthedocs.io/en/latest/codingstyle/zcml-style.html

I am thinking about adding a `--zcml` flag.

**Comment by gforcada** [comment]
Another thing with ZCML that I noticed is that it lowercases **all** attributes, which for some reason made bin/instance fail to start, so in ZCML at least the casing should be respected (maybe whitelist some known attributes would be better)

**Comment by ale-rt** [comment]
I declare this one closed.

You can try it using the `--zcml` or `-z` parameters.

If you want some modification (e.g. a different order for the attributes) just let me know.
