### ISSUE TITLE
XML entities are removed

### ISSUE THREAD

**Issue by jensens** [collective/zpretty#48]
`git diff` after `zpretty -ix profiles/default/types/tfv.mitglieder.xml`
```
   <property name="description"
             i18n:translate=""
-  >Top Level Container f&uuml;r alle Reviere</property>
+  >Top Level Container fr alle Reviere</property>
```

**Comment by agitator** [comment]
In my case with zpretty-2.1.0, py3

a workflow definition with `ö` was changed to `>ver&ouml;ffentlichen</action>`

**Comment by jensens** [comment]
State: Latest zpretty, problem is still there.

**Comment by ale-rt** [comment]
Sorry I did not have time to check this, thanks for reporting

**Comment by ale-rt** [comment]
The example you provided should be properly formatted by:

https://pypi.org/project/zpretty/2.3.0a4/

Sorry for the delay :)

**Comment by jensens** [comment]
Yay!
