### ISSUE TITLE
HTML entities in <script> code

### ISSUE THREAD

**Issue by thet** [collective/zpretty#57]
This line:

```
<script>
    var form = jQuery("<form>");
</script>
```

is changed by ``zpretty -i`` into:
```
<script>
    var form = jQuery("&lt;form&gt;");
</script>
```

The change of HTML entities within ``<script>`` tags and probably also ``<style>`` tags should be prevented.

**Comment by ale-rt** [comment]
I released an alpha version (2.3.0a3) that should have this fixed
