### ISSUE TITLE
XML: changes single space to multiple lines

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/zpretty#64]
In a [`registry.xml`](https://github.com/collective/collective.classifiers/blob/maurits-code-analysis/collective/classifiers/profiles/testfixture/registry.xml) I have an element with a single space. `zpretty` changes it to a newline with spaces:

```
-        <element> </element>
+        <element>
+        </element>
```

This gives a validation error, because this is an element for a `TextLine` and this cannot contain a newline.
(I am not completely sure why this file has a space here, but there is a comment saying it is intentional.)

It also swallows a non-ascii character (though not all) in the same file. See the [commit message](https://github.com/collective/collective.classifiers/commit/ed3fb36626d010786e2cf7c67772e123218f39c4) from the commit where I add code-analysis/quality.

**Comment by mauritsvanrees** [comment]
I made a draft PR for the affected package, that is easier: https://github.com/collective/collective.classifiers/pull/6

**Comment by ale-rt** [comment]
Thanks for reporting!
I think there is some code that prevents zpretty to fiddle with spaces in `<pre>` elements. 
Most probably I have to change the XML prettifier to preserve spaces in any xml tag.

**Comment by ale-rt** [comment]
Please try with `zpretty==2.3.0a2`.

With that I have:
```
$ wget https://raw.githubusercontent.com/collective/collective.classifiers/maurits-code-analysis/collective/classifiers/profiles/testfixture/registry.xml -O original.xml
$ diff original.xml <(./bin/zpretty original.xml)
27c27
<         <!-- This space intentionally left blank. -->
---
>       <!-- This space intentionally left blank. -->
```

**Comment by mauritsvanrees** [comment]
I have tried `zpretty==2.3.0a3` and that works. Thanks!

After a final release, we should update [`code-quality`](https://github.com/plone/code-quality/blob/main/requirements.txt)
