### ISSUE TITLE
Add option to ignore a specific file

### ISSUE THREAD

**Issue by wesleybl** [collective/zpretty#71]
I have an xml file to configure the `model_source` field of a dexterity type:

```xml
...
 <property name="model_source">&lt;model xmlns:i18n=&quot;http://xml.zope.org/namespaces/i18n&quot; xmlns:marshal=&quot;http://namespaces.plone.org/supermodel/marshal&quot; xmlns:form=&quot;http://namespaces.plone.org/supermodel/form&quot; xmlns:security=&quot;http://namespaces.plone.org/supermodel/security&quot; xmlns:indexer=&quot;http://namespaces.plone.org/supermodel/indexer&quot; xmlns:lingua=&quot;http://namespaces.plone.org/supermodel/lingua&quot; xmlns:users=&quot;http://namespaces.plone.org/supermodel/users&quot; xmlns=&quot;http://namespaces.plone.org/supermodel/schema&quot;&gt;
...
</property>
```

I'm using zpretty as lint and it complains about this file. When formatting the file, it removes the `&lt;` and `&gt;`. But these characters are necessary for the `model_source` field to work. Is this an error?

It would be nice to have an option to ignore this specific file. Today I have to disable lint zpretty, because of this.

Do I have any options?

**Comment by ale-rt** [comment]
Which version are you using?
There is an alpha version I prepared some time ago that might be free from this issue.
- https://pypi.org/project/zpretty/2.3.0a3/

If you are using it with pre-commit you can add an exclude patterrn:

- https://pre-commit.com/#top_level-exclude

**Comment by ale-rt** [comment]
Can you provide a minimum valid xml file that shows the error?

**Comment by wesleybl** [comment]
The file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<object name="Type" meta_type="Dexterity FTI" i18n:domain="plone"
   xmlns:i18n="http://xml.zope.org/namespaces/i18n">
<property name="model_source">&lt;model&quot;teste&lt;/model&gt;</property>
</object>
```

The result:
$ ./bin/zpretty teste.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<object xmlns:i18n="http://xml.zope.org/namespaces/i18n"
        meta_type="Dexterity FTI"
        name="Type"
        i18n:domain="plone"
>
  <property name="model_source">modelteste/model</property>
</object>
```

Any clues as to who is the villain?

**Comment by ale-rt** [comment]
No clue, but I will look in to that

**Comment by ale-rt** [comment]
This is probably related to #48

**Comment by ale-rt** [comment]
@wesleybl the example you provided should be properly formatted by:

- https://pypi.org/project/zpretty/2.3.0a4/

About adding the option to ignore a specific file, I do not see that happening given that now you have to actively pass files to zpretty.

You can add an issue to do that in the [code-quality repo](https://github.com/plone/code-quality)

**Comment by ale-rt** [comment]
Please open another issue if you find other problems!
Thanks for reporting and sorry for the delay :)
