### ISSUE TITLE
feature request: preserve CDATA

### ISSUE THREAD

**Issue by PeterMosmans** [collective/zpretty#76]
Hi,
Thanks for the great tool. Currently, when formatting XML files, the CDATA elements are stripped. Input example snippet:
```
  <pre><![CDATA[
JACK
]]></pre>
```

Output:
```
    <pre>
JACK
</pre>
```

Apparently the lxml library, used by BeautifulSoup, can be instructed to not replace CDATA tags, see https://lxml.de/api/lxml.etree.HTMLParser-class.html (`strip_cdata=False`).
Would you be open to adding this feature, where it will be customizable whether CDATA will be stripped or not? If so, I could take a stab at it?

**Comment by ale-rt** [comment]
Hi @PeterMosmans, thanks for reporting and for the insight.
Every contribution is very welcome :)

**Comment by ale-rt** [comment]
I actually removed a custom tree builder in #70 that had `strip_cdata=False`, see https://github.com/collective/zpretty/pull/70/files#diff-c86a5635dd260776eea05226dec43f5e6f7b4c07ac185b3ec2d210401000a743L63
I think #79 is a valid fix for this issue (which I consider more a bug than a feature request).

**Comment by PeterMosmans** [comment]
Thanks @ale-rt for your fast implementation. Yeah, BeautifulSoup is a bit limited sometimes, that workaround is 👍 
This works for CDATA - however, it 'still' messes up entities. Shall I open another issue for that ?

**Comment by ale-rt** [comment]
Thanks for checking! 
I opened #80.
If you have more issue do not be afraid to open new ones yourself!

And if you want to try to submit a patch you are as well welcome!
