### ISSUE TITLE
Wrong format with newline in multiline tag 

### ISSUE THREAD

**Issue by jensens** [collective/zpretty#84]
If I have a XML with a newline like this:

```
  <object meta_type="Dexterity FTI"

          name="tfv.kurs.tn"
  />
```

I got wrongly this:

```
  <object meta_type="Dexterity FTI">
          name="tfv.kurs.tn"
  /&gt;
```

After removing the newline all is fine.

**Comment by ale-rt** [comment]
Try if this branch works please: https://github.com/collective/zpretty/compare/84.fixed?expand=1

I will try do make a meaningful PR with some tests later.
